"""Execution Telemetry

Revision ID: 2c5b823a0d24
Revises: 3541a51b9881
Create Date: 2026-09-30 08:03:04.901428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c5b823a0d24'
down_revision: Union[str, None] = '3541a51b9881'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('requested_price', sa.Float(), nullable=True))
    op.add_column('trades', sa.Column('slippage', sa.Float(), nullable=True))
    op.add_column('trades', sa.Column('retcode', sa.Integer(), nullable=True))
    op.add_column('trades', sa.Column('broker_comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'broker_comment')
    op.drop_column('trades', 'retcode')
    op.drop_column('trades', 'slippage')
    op.drop_column('trades', 'requested_price')
    # ### end Alembic commands ###
