"""Add AccountSnapshot

Revision ID: 3541a51b9881
Revises: 4ebe2e97768c
Create Date: 2026-09-30 07:08:24.732947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3541a51b9881'
down_revision: Union[str, None] = '4ebe2e97768c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('day_start_equity', sa.Float(), nullable=True),
    sa.Column('peak_equity', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_snapshots_id'), 'account_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_account_snapshots_timestamp'), 'account_snapshots', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_account_snapshots_timestamp'), table_name='account_snapshots')
    op.drop_index(op.f('ix_account_snapshots_id'), table_name='account_snapshots')
    op.drop_table('account_snapshots')
    # ### end Alembic commands ###
