"""Add broker deal id

Revision ID: 4ebe2e97768c
Revises: c63b3df48345
Create Date: 2026-09-30 07:04:19.653617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ebe2e97768c'
down_revision: Union[str, None] = 'c63b3df48345'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('broker_deal_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_trades_broker_deal_id'), 'trades', ['broker_deal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_broker_deal_id'), table_name='trades')
    op.drop_column('trades', 'broker_deal_id')
    # ### end Alembic commands ###
