"""Add SL TP to Trade

Revision ID: 72e0a3cf73ad
Revises: d52c639bf803
Create Date: 2026-09-29 17:45:08.896913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72e0a3cf73ad'
down_revision: Union[str, None] = 'd52c639bf803'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('stop_loss', sa.Float(), nullable=True))
    op.add_column('trades', sa.Column('take_profit', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'take_profit')
    op.drop_column('trades', 'stop_loss')
    # ### end Alembic commands ###
