"""Add broker ids

Revision ID: c63b3df48345
Revises: 72e0a3cf73ad
Create Date: 2026-09-29 21:20:45.762062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c63b3df48345'
down_revision: Union[str, None] = '72e0a3cf73ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('broker_order_id', sa.String(), nullable=True))
    op.add_column('trades', sa.Column('broker_position_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_trades_broker_order_id'), 'trades', ['broker_order_id'], unique=False)
    op.create_index(op.f('ix_trades_broker_position_id'), 'trades', ['broker_position_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_broker_position_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_broker_order_id'), table_name='trades')
    op.drop_column('trades', 'broker_position_id')
    op.drop_column('trades', 'broker_order_id')
    # ### end Alembic commands ###
